### ISSUE TITLE
Rename `Dnsimple.Record` to `Dnsimple.ZoneRecord`

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-elixir#18]
To match the go and ruby clients.

**Comment by jacegu** [comment]
In the [Ruby client](https://github.com/aetrion/dnsimple-ruby/blob/master/lib/dnsimple/struct/record.rb) it is called `Record` too. However in the [Go client](https://github.com/aetrion/dnsimple-go/blob/master/dnsimple/zones_records.go) it's called `ZoneRecord`.

@aeden @weppos @jodosha which one should we use?

**Comment by aeden** [comment]
My understanding is @weppos is considering the Go client to be the reference implementation, but he'll need to confirm.

**Comment by weppos** [comment]
It was originally called `Record` in the Go client as well, but it was renamed as part of the shift to V2. I should have renamed the Ruby client as well (actually I believe we talked about that and I assumed it was done).

Both the Ruby and the Go client are kind of reference, but the Go one is generally a little bit more accurate as it's the one I've been spending most time on and was almost rewritten from 0. Moreover, Go is a more strict language, and some decisions were influenced by the Go client because it was the hardest to please so far.

I vote to rename both the Ruby and Elixir client to ZoneRecord.

**Comment by weppos** [comment]
PS. Here's the relevant commit https://github.com/aetrion/dnsimple-go/commit/ef7339c1ae1dc5aee1d5049e097fd5bee221c66c

**Comment by jacegu** [comment]
Does that mean that we should have a different data structure (or object) for records in other contexts (e.g templates) ?

**Comment by weppos** [comment]
> Does that mean that we should have a different data structure (or object) for records in other contexts (e.g templates) ?

That's correct, it has always been like this. We always had Record vs TemplateRecord (which was one of the reason why I wanted to be more explicit on the name).
